version: '3.8'

services:
  memcached:
    image: memcached:latest
    container_name: my_memcached
    restart: unless-stopped
    ports:
      - "11211:11211"
    command: memcached -m 64  # Allocates 64MB memory
