version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=mysecretpassword

volumes:
  redis_data:
    driver: local
